{
 "title": "Device Performance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "label": "Device",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurementTagValues(\r\n  bucket: \"${Bucket}\",\r\n  measurement: \"DevicePerformance\",\r\n  tag: \"Device_id\"\r\n)\r\n"
   },
   { "name": "Bucket", "label": "Bucket", "query": "NewDSS" }
  ]
 },
 "panels": [
  {
   "title": "System Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Agent Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\n  |> range(start: -90d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Processor\")\n  |> filter(fn: (r) =>  r[\"_field\"] == \"CpuProcessorUtility\" )\n  |> last()\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _measurement: r._measurement,\n        Status: if exists r._value and (uint(v: now()) - uint(v: r._time)) < 60000000000 then \"Live\" else \"Offline\"\n    }))\n  |> yield(name: \"uptime_on_off\")\n"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Processor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"SystemUpTime\")\r\n  |> last()\r\n"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Battery\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Voltage\")\r\n"
      },
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Designed Capacity\" or r[\"_field\"] == \"Full Charged Capacity\")\r\n\r\n  |> last()\r\n  |> distinct(column: \"_value\")\r\n  |> group(columns: [\"_time\"])\r\n  |> pivot(rowKey:[\"_measurement\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => {\r\n      batteryPercentage = if exists r[\"Full Charged Capacity\"] and exists r[\"Designed Capacity\"] and r[\"Designed Capacity\"] != 0.0 then (float(v: r[\"Full Charged Capacity\"]) / float(v: r[\"Designed Capacity\"])) * 100.0 else 0.0\r\n      return {\r\n          _measurement: r._measurement,\r\n          \"Battery Capacity (%)\": batteryPercentage\r\n      }\r\n  })"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Processor\" or r[\"Metrics_type\"] == \"Disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ProcessorQueueLength\" or r[\"_field\"] == \"CurrentDiskQueueLength\")\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n  |> last()",
       "select": [
        [
         { "params": [ "total_threads" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Current Resource Utilization",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Memory\" or r[\"Metrics_type\"] == \"Processor\" or r[\"Metrics_type\"] == \"Disk\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"CpuProcessorUtility\" or r[\"_field\"] == \"MemoryUsagePercentage\" or r[\"_field\"] == \"DiskSpaceUsagePercentage\")\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n  |> last()\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"Device_id\", \"CpuProcessorUtility\", \"MemoryUsagePercentage\", \"DiskSpaceUsagePercentage\"])\r\n  |> rename(columns: {\r\n      \"_time\": \"Time\",\r\n      \"CpuProcessorUtility\": \"CPU Usage (%)\",\r\n      \"DiskSpaceUsagePercentage\": \"Disk Usage (%)\",\r\n      \"MemoryUsagePercentage\": \"Memory Usage (%)\"\r\n  })\r\n"
      },
      {}
     ]
    },
    {
     "title": "Device Information",
     "type": "table",
     "gridPos": { "h": 15, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -10d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"SystemInfo\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"CSName\", \"Model\", \"Manufacturer\",  \r\n                    \"BiosName\", \"ProcessorName\", \"ProcessorCores\", \"TotalDiskSizeGB\",\"ProcessorLogicalProcessors\", \"OSArchitecture\", \"OSInstallDate\", \"OSName\", \r\n                    \"TotalMemoryGB\", \"PowerPlanName\", \"ProcessorMaxClockSpeed\"])\r\n    |> rename(columns: {\r\n      Model: \"Model Name\",\r\n      Manufacturer: \"Manufacturer\",\r\n      TotalDiskSizeGB: \"Disk Size (GB)\",\r\n      CSName: \"Device Name\",\r\n      BiosName: \"BIOS Version\",\r\n      ProcessorName: \"Processor\",\r\n      ProcessorMaxClockSpeed: \"Processor Max Speed\",\r\n      ProcessorCores: \"Processor Cores (Physical)\",\r\n      ProcessorLogicalProcessors: \"Processor Cores (Virtual)\",\r\n      OSArchitecture: \"System Architecture\",\r\n      OSInstallDate: \"OS Installation Date\",\r\n      OSName: \"Operating System\",\r\n      TotalMemoryGB: \"RAM Size (GB)\",\r\n      PowerPlanName: \"Power Plan\"\r\n  })\r\n"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n    |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Processor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Threads\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "total_threads" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n    |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Processor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Processes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "total_threads" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU and Memory Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Memory\" or r[\"Metrics_type\"] == \"Processor\" or r[\"Metrics_type\"] == \"Disk\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"CpuProcessorUtility\" or r[\"_field\"] == \"MemoryUsagePercentage\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"Device_id\", \"CpuProcessorUtility\", \"MemoryUsagePercentage\"])\r\n  |> rename(columns: {\r\n      \"_time\": \"Time\",\r\n      \"CpuProcessorUtility\": \"CPU Usage (%)\",\r\n      \"MemoryUsagePercentage\": \"Memory Usage (%)\"\r\n  })\r\n"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Processor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ContextSwitchesPerSec\" )\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n"
      }
     ]
    },
    {
     "title": "Laptop State",
     "type": "state-timeline",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MemoryUsagePercentage\")\n\n  |> aggregateWindow(every: 1m, fn: last)\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _measurement: r._measurement,\n        _field: r._field,\n        _value: if exists r._value then 0 else 1\n    }))\n  |> yield(name: \"uptime_on_off\")\n"
      }
     ]
    },
    {
     "title": "Event Logs Source",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"NewDSS\") \r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) =>\r\n    r[\"EventSource\"] == \"Application Error\" or\r\n    r[\"EventSource\"] == \"Application Hang\" or\r\n    r[\"EventSource\"] == \"Microsoft-Windows-Kernel-Power\" or\r\n    r[\"EventSource\"] == \"Bugcheck\"\r\n  )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TimeGenerated\")\r\n  |> group(columns: [\"EventSource\"])\r\n  |> count()\r\n  |> keep(columns: [\"EventSource\", \"_value\"])\r\n"
      }
     ]
    },
    {
     "title": "Application Faults & Error",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) =>\r\n    r[\"EventSource\"] == \"Application Error\" or\r\n    r[\"EventSource\"] == \"Application Hang\" or\r\n    r[\"EventSource\"] == \"Microsoft-Windows-Kernel-Power\" or\r\n    r[\"EventSource\"] == \"Bugcheck\"\r\n  )\r\n  // grab only relevant fields\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TimeGenerated\" or r[\"_field\"] == \"ApplicationName\")\r\n  // pivot to get both fields on the same row\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  // now ApplicationName is in a real column!\r\n  |> group(columns: [\"ApplicationName\"])\r\n  |> count(column: \"TimeGenerated\")\r\n  |> rename(columns: { TimeGenerated: \"\" })\r\n  |> keep(columns: [\"ApplicationName\", \"\"])\r\n"
      }
     ]
    },
    {
     "title": "Event Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) =>\r\n    r[\"EventSource\"] == \"Application Error\" or\r\n    r[\"EventSource\"] == \"Application Hang\" or\r\n    r[\"EventSource\"] == \"Microsoft-Windows-Kernel-Power\" or\r\n    r[\"EventSource\"] == \"Bugcheck\"\r\n  )\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => exists r[\"Message\"] and exists r[\"EventID\"])\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Series Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Processor\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"ProcessorTime\" or r[\"_field\"] == \"CpuUserModeTime\" or r[\"_field\"] == \"CpuKernelModeTime\")\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n"
      }
     ]
    },
    {
     "title": "CPU Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Processor\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"CpuProcessorUtility\")\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n"
      }
     ]
    },
    {
     "title": "Memory Utilization %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Memory\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"MemoryUsagePercentage\")\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n"
      }
     ]
    },
    {
     "title": "Memory Usage (GB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PhysicalUsedGB\" or r[\"_field\"] == \"PhysicalFreeGB\")\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n"
      }
     ]
    },
    {
     "title": "Disk Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Disk\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"DiskSpaceUsagePercentage\")\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n"
      }
     ]
    },
    {
     "title": "AvgDiskQueueLength",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Disk\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"AvgDiskQueueLength\")\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processor Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Processor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ProcessorQueueLength\" )\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Processor\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"Threads\")\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DevicePerformance\")\r\n  |> filter(fn: (r) => r[\"Device_id\"] == \"${Device}\")\r\n  |> filter(fn: (r) => r[\"Metrics_type\"] == \"Processor\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"Processes\")\r\n  |> drop(columns: [\"Metrics_type\",\"Device_id\"])\r\n"
      }
     ]
    }
   ]
  }
 ]
}